### ISSUE TITLE
Can't find module when running app created by pyinstaller

### ISSUE THREAD

**Issue by MichaelMMeskhi** [gordthompson/sqlalchemy-access#10]
Hello, I posted [this issue](https://stackoverflow.com/questions/63699178/pyinstaller-not-including-module). When I connect to my Access file as you suggest, in Jupyter Notebook, things work with no problem. Same goes with running things in Python shell.

**Comment by gordthompson** [comment]
Try adding the following two imports to your main Python script (i.e., the .py file you would run to start your application in Python itself) and then use pyinstaller to rebuild your executable:

``` python
import sqlalchemy_access as sa_a
import sqlalchemy_access.pyodbc as sa_a_pyodbc
```

**Comment by MichaelMMeskhi** [comment]
@gordthompson Thanks for getting back to me. Unfortunately the problem still persists. 

These are all my imports:

```python
import sqlalchemy_access as sa_a
import sqlalchemy_access.pyodbc as sa_a_pyodbc 
from sqlalchemy import *
from sqlalchemy.engine import create_engine
from sqlalchemy.schema import *
```

And my code does this:

```python
copy2(os.path.join(dir_path, f"data\\{graph_name}\\raw\\{file_name}"), os.path.join(dir_path, f"data\\{graph_name}\\results\\{file_name}"))
db_file_path = os.path.join(dir_path, f"data\\{graph_name}\\results\\{file_name}")
connection_string = (r'DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};' f'DBQ={db_file_path};' r'ExtendedAnsiSQL=1;')
connection_url = f'access:///?odbc_connect={urllib.parse.quote_plus(connection_string)}'
engine = create_engine(connection_url)
text_labels.to_sql('InstTextLabels', engine, index=False, if_exists='append')
```

Raised error is:

```python
Traceback (most recent call last):
  File "solver.py", line 507, in <module>
    main()
  File "solver.py", line 503, in main
    export_results(file_name, graph_name, downstream_low, downstream_high, objective_results, objective_fuses, objective_recloseres, nodes, text_labels, dir_path)
  File "solver.py", line 403, in export_results
    engine = create_engine(connection_url)
  File "sqlalchemy\engine\__init__.py", line 479, in create_engine
  File "sqlalchemy\engine\strategies.py", line 61, in create
  File "sqlalchemy\engine\url.py", line 172, in _get_entrypoint
  File "sqlalchemy\util\langhelpers.py", line 267, in load
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:access
[6132] Failed to execute script solver
```

**Comment by gordthompson** [comment]
Have you tried both ways of building an .exe (the regular way, and the single-file way)? FWIW, the following compiles and runs fine using 32-bit Python 3.8:

``` python
import urllib

import msaccessdb
import pandas as pd
import sqlalchemy as sa
import sqlalchemy_access as sa_a
import sqlalchemy_access.pyodbc as sa_a_pyodbc

mdb_path = r"C:\Users\Public\pyinstaller_test.mdb"

msaccessdb.create(mdb_path)  # overwrites if exists

connection_string = (
    "DRIVER={Microsoft Access Driver (*.mdb)};"
    f"DBQ={mdb_path};"
    "ExtendedAnsiSQL=1;"
)
connection_uri = f"access+pyodbc:///?odbc_connect={urllib.parse.quote_plus(connection_string)}"
engine = sa.create_engine(connection_uri)

df = pd.DataFrame([(1, "foo"), (2, "bar")], columns=["id", "txt"])
df.to_sql("table1", engine, index=False, if_exists="replace")

with engine.begin() as conn:
    result = conn.execute(sa.text("SELECT * FROM table1")).fetchall()
    print(result)
    """console output:
    [(1, 'foo'), (2, 'bar')]
    """
```

**Comment by MichaelMMeskhi** [comment]
@gordthompson I believe I have managed to get the issue fixed. I tested it using your code above since it worked without a problem. I also installed the access driver from Microsoft. I don't know if that helped the issue or not. The only thing that happens now, is that I get this warning message.

`sqlalchemy\engine\reflection.py:805: SAWarning: The Access ODBC driver does not support the ODBC "SQLPrimaryKeys" function. get_pk_constraint() is returning an empty list.`

Thank you so much for helping out!

**Comment by gordthompson** [comment]
That warning is a recent addition (within the last couple of days). Previously the `get_pk_constraint()` function silently returned an empty list, but I thought it would be better to emit a warning when SQLAlchemy reflection calls it.

For more information re: PK reflection see #9 .
