### ISSUE TITLE
Data source name not found and no default driver specified

### ISSUE THREAD

**Issue by Cazforshort** [gordthompson/sqlalchemy-access#13]
I get the following error:
`sqlalchemy.exc.InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')`

when running your DSN-less connection 

`        connecion= 'DBQ='+connecion+';'
        connecion= repr(connecion)[:-1][1:]
        
        connection_string = (
        r'DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};'+
        connecion+
        r'ExtendedAnsiSQL=1;'
        )
        
        connection_uri = f"access+pyodbc:///?odbc_connect={urllib.parse.quote_plus(connection_string)}"
        engine = create_engine(connection_uri)`

Are there some dependency steps that I'm missing? The resulting connection string looks good:

`DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=C:\\Users\\cc667216\\Documents\\Test_Access_Database.accdb;ExtendedAnsiSQL=1;`

Also when I tried to just use a DSN for the db I got the following error:
`The specified DSN contains an architecture mismatch between the Driver and Application (0) (SQLDriverConnect)')`

**Comment by gordthompson** [comment]
You can use the [AceOdbcCheck](https://github.com/gordthompson/AceOdbcCheck) utility to check whether the ACE driver is installed and if it is 64-bit or 32-bit. You need to use the same "bitness" of Python.

**Comment by Cazforshort** [comment]
Ah 64 bit python and 32 bit driver.

**Comment by gordthompson** [comment]
That explains it.
