### ISSUE TITLE
sqlalchemy.func.lower not working

### ISSUE THREAD

**Issue by txemi** [gordthompson/sqlalchemy-access#16]
Next query fails:

```
res1 = session.query(mov_class.dest).filter(
            sqlalchemy.func.lower(mov_class.concept) == sqlalchemy.func.lower(concept)).all()
```

the log:

`sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY000', '[HY000] [Microsoft][Controlador ODBC Microsoft Access] Error reservado (-1001); no hay ningún mensaje para este error. (-1001) (SQLExecDirectW)')
[SQL: SELECT mov.dest AS mov_dest 
FROM mov 
WHERE lower(mov.concept) = lower(?)]
[parameters: ('blablablabla',)]
(Background on this error at: https://sqlalche.me/e/14/dbapi)`

Not sure if could be a hint that **lower** in access should be **Lcase**

Thanks,

**Comment by txemi** [comment]
I also tryed ilike with same result:

`        res1 = session.query(mov_class.dest).filter(
            mov_class.concepto.ilike('%' + concept + '%')).all()`

**Comment by gordthompson** [comment]
**re: `.lower()`**

You're right; Access SQL uses `LCase()` so you need to use `func.lcase()` for that:

```python
tbl = sa.Table(
    "gh_16",
    sa.MetaData(),
    sa.Column("id", sa.Integer, primary_key=True),
    sa.Column("txt", sa.Unicode(10)),
)
tbl.drop(engine, checkfirst=True)
tbl.create(engine)

with engine.begin() as conn:
    conn.execute(
        tbl.insert(), [dict(txt=x) for x in ["foobar", "FooBar", "FOOBAR"]]
    )

with engine.begin() as conn:
    result = conn.execute(
        sa.select(tbl.c.id, sa.func.lcase(tbl.c.txt))
    ).fetchall()
    print(result)
    # [(1, 'foobar'), (2, 'foobar'), (3, 'foobar')]
```

**re: `.ilike()`**

Access SQL `LIKE` queries are already case-insensitive, so you can just use this:

```python
    result = conn.execute(
        sa.select(tbl).where(tbl.c.txt.like("foobar"))
    ).fetchall()
    print(result)
    # [(1, 'foobar'), (2, 'FooBar'), (3, 'FOOBAR')]
```

**Comment by txemi** [comment]
Thank you very much, I will try this.
