### ISSUE TITLE
SADeprecation Warning

### ISSUE THREAD

**Issue by latot** [gordthompson/sqlalchemy-access#21]
Hi, when we try create an engine we are getting this warning:

```
engine = sa.create_engine(connection_url)
<stdin>:1: SADeprecationWarning: The dbapi() classmethod on dialect classes has been renamed to import_dbapi().  Implement an import_dbapi() classmethod directly on class <class 'sqlalchemy_access.pyodbc.AccessDialect_pyodbc'> to remove this warning; the old .dbapi() classmethod may be maintained for backwards compatibility.
```

Thx!

**Comment by gordthompson** [comment]
That issue was addressed in 8c8f6e42 and included in sqlalchemy-access 2.0.0. Please ensure that you are using the latest (2.x) versions of SQLAlchemy and sqlalchemy-access.

**Comment by latot** [comment]
Hi, @gordthompson I'm using 2.0.17 with latest ```sqlalchemy-access```

**Comment by gordthompson** [comment]
What do you see if you add the following to your script?

```python
import sqlalchemy_access as sa_a; print(sa_a.__version__)
```

**Comment by latot** [comment]
```
import sqlalchemy_access as sa_a; print(sa_a.__version__)
1.0.8
```

Installed rn from pip

**Comment by gordthompson** [comment]
sqlalchemy-access 1.0.8 is very old (2020-10-24). The latest version is 2.0.2 (2023-05-26). I don't know why pip would give you such an old version. You might try downloading the latest wheel file

https://files.pythonhosted.org/packages/ab/23/ab5a62f9ff084dedfbe4d9b737278c9eb59f158f36e7d26df24aca2ec452/sqlalchemy_access-2.0.2-py3-none-any.whl

and install it via 

```
pip install sqlalchemy_access-2.0.2-py3-none-any.whl
```

**Comment by latot** [comment]
Oks, this shows half of this:

```
Processing ./sqlalchemy_access-2.0.2-py3-none-any.whl
Requirement already satisfied: SQLAlchemy>=2.0.0 in /home/pipe/pyenv/lib/python3.11/site-packages (from sqlalchemy-access==2.0.2) (2.0.23)
Requirement already satisfied: pyodbc>=4.0.27 in /home/pipe/pyenv/lib/python3.11/site-packages (from sqlalchemy-access==2.0.2) (5.0.1)
INFO: pip is looking at multiple versions of sqlalchemy-access to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement pywin32 (from sqlalchemy-access) (from versions: none)
ERROR: No matching distribution found for pywin32
```

I'm on Linux, so is normal to pywin32 don't exists and be problems there, the solution is already done with the other issue.

Now.... the other half... why is installing the 1.0.8? no idea.
Is possible to apply to all versions the SO fix?

**Comment by gordthompson** [comment]
Okay, 1.0.8 was the last version before 1.1.0, the version that added the pywin32 dependency.

The dialect does not support Linux, so there is nothing more to do here. Sorry.
